// tokens.js — Single Source of Truth fuer das Design-System (Stillwater / Werkbank-HUD).
// In JS definiert, damit Logik + Framer dieselben Werte lesen. Per applyTokens()
// werden sie zur Laufzeit als CSS-Custom-Properties auf :root gespiegelt → driftfrei.

export const tokens = {
  color: {
    bg: "#0E1518",
    bg2: "#0A0F12",
    pan: "#142127",
    pan2: "#17262C",
    teal: "#4FD2C2",
    ember: "#FFA24D",
    warn: "#E8745C",
    warnSoft: "rgba(232,116,92,0.12)",
    warnEdge: "rgba(232,116,92,0.30)",
    ink: "#E8F0EE",
    dim: "#86999A",
    edge: "rgba(79,210,194,.16)",
    ok: "#5FE3A1",
    okSoft: "rgba(95,227,161,0.12)",
    okEdge: "rgba(95,227,161,0.30)",
  },
  font: {
    body: "'Space Grotesk', system-ui, sans-serif",
    mono: "'JetBrains Mono', ui-monospace, monospace",
  },
  radius: {
    sm: "8px",
    md: "10px",
    lg: "14px",
  },
  space: {
    1: "4px",
    2: "8px",
    3: "12px",
    4: "16px",
    5: "24px",
    6: "32px",
    7: "48px",
    8: "64px",
  },
  fontSize: {
    display: "28px",
    h1: "22px",
    h2: "18px",
    h3: "16px",
    body: "15px",
    sm: "13px",
    label: "12px",
    micro: "11px",
  },
  lineHeight: { tight: "1.2", base: "1.5", relaxed: "1.65" },
  letterSpacing: { eyebrow: "0.2em", tight: "-0.01em" },
  grid: "26px",
};

// Mapping tokens -> CSS-Custom-Properties. Einzige Stelle, die Namen vergibt.
export const cssVars = {
  "--c-bg": tokens.color.bg,
  "--c-bg2": tokens.color.bg2,
  "--c-pan": tokens.color.pan,
  "--c-pan2": tokens.color.pan2,
  "--c-teal": tokens.color.teal,
  "--c-ember": tokens.color.ember,
  "--c-warn": tokens.color.warn,
  "--c-warn-soft": tokens.color.warnSoft,
  "--c-warn-edge": tokens.color.warnEdge,
  "--c-ink": tokens.color.ink,
  "--c-dim": tokens.color.dim,
  "--c-edge": tokens.color.edge,
  "--c-ok": tokens.color.ok,
  "--c-ok-soft": tokens.color.okSoft,
  "--c-ok-edge": tokens.color.okEdge,
  "--font-body": tokens.font.body,
  "--font-mono": tokens.font.mono,
  "--radius-sm": tokens.radius.sm,
  "--radius-md": tokens.radius.md,
  "--radius-lg": tokens.radius.lg,

  "--space-1": tokens.space[1],
  "--space-2": tokens.space[2],
  "--space-3": tokens.space[3],
  "--space-4": tokens.space[4],
  "--space-5": tokens.space[5],
  "--space-6": tokens.space[6],
  "--space-7": tokens.space[7],
  "--space-8": tokens.space[8],

  "--fs-display": tokens.fontSize.display,
  "--fs-h1": tokens.fontSize.h1,
  "--fs-h2": tokens.fontSize.h2,
  "--fs-h3": tokens.fontSize.h3,
  "--fs-body": tokens.fontSize.body,
  "--fs-sm": tokens.fontSize.sm,
  "--fs-label": tokens.fontSize.label,
  "--fs-micro": tokens.fontSize.micro,

  "--lh-tight": tokens.lineHeight.tight,
  "--lh-base": tokens.lineHeight.base,
  "--lh-relaxed": tokens.lineHeight.relaxed,

  "--ls-eyebrow": tokens.letterSpacing.eyebrow,
  "--ls-tight": tokens.letterSpacing.tight,

  "--grid": tokens.grid,
};
